---
title: "How do differences in the ability to control attention relate to cognition and well-being?"

description: "People differ in their ability to control attention, and these differences are a fundamental aspect of human cognition. We investigate how individual differences in attention control play a role in shaping our perception, memory, reasoning, and well-being."

listing:
  - id: measurement
    contents:
      - ../../publications/2020/wms-book-chapter/index.qmd
      - ../../publications/2021/jepg-toolbox-1/index.qmd
      - ../../publications/2021/jepg-visualarrays/index.qmd
      - ../../publications/2023/brm-toolbox-2/index.qmd
      - ../../publications/2023/jepg-squared-intro/index.qmd
      - ../../publications/2023/sact-2/index.qmd
    sort:
      - "pub-status asc"
      - "date desc"
    template: ../../assets/listings/pub-listing-scroll.ejs.md
    fields: [title, pub-year, pub-authors, venue, pub-status, pub-type, pdf, path]

  - id: sensation
    contents:
      - ../../publications/2020/app-sensory-discrimination/index.qmd
      - ../../publications/2025/jepg-inspection/index.qmd
    sort:
      - "pub-status asc"
      - "date desc"
    template: ../../assets/listings/pub-listing-scroll.ejs.md
    fields: [title, pub-year, pub-authors, venue, pub-status, pub-type, pdf, path]

  - id: cognition
    contents:
      - ../../publications/2020/lm-diff-exp/index.qmd
      - ../../publications/2021/tr-rationality/index.qmd
      - ../../publications/2022/chwml-book-chapter/index.qmd
      - ../../publications/2022/int-pot/index.qmd
      - ../../publications/2023/jepg-squared-intro/index.qmd
      - ../../publications/2024/ac-psychomotor/index.qmd
      - ../../publications/2025/front-climate/index.qmd
      - ../../publications/2025/ijsa-navy/index.qmd
    sort:
      - "pub-status asc"
      - "date desc"
    template: ../../assets/listings/pub-listing-scroll.ejs.md
    fields: [title, pub-year, pub-authors, venue, pub-status, pub-type, pdf, path]

link: ""

order: 1
page-layout: full
---

## Measurement and Individual Differences

::: {.profile-section-card}

Critical to understanding the role of attention control in cognition and well-being is the ability to measure it. We investigate how to best measure attention control, including the development of new tasks and approaches to measuring attention control in real-world contexts.

[View and Download Attention Tasks →](#measurement){.link-cta}

:::

### Publications {.before-adjust}

::: {#measurement}
:::

## Sensation and Perception

::: {.profile-section-card}

Attention control plays a critical role in shaping our perception of the world around us. We investigate how individual differences in attention control influence sensory processing and perceptual experience, including phenomena such as sensory discrimination, perceptual stability, and the integration of sensory information across modalities.

:::

### Publications {.before-adjust}

::: {#sensation}
:::


## Higher-Order Cognition

::: {.profile-section-card}

Higher-order cognitive processes, such as working memory, executive function, and fluid intelligence, are influenced by individual differences in attention control. We explore how these differences impact performance in complex cognitive tasks and real-world applications.
:::

::: {#cognition}
:::

## Real-World Success

## Well-Being
